services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-solid
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
